// Generated by CoffeeScript 1.6.3
(function() {
  var embeddedJS;

  exports.generateMap = (require('./generateMap')).generateMap;

  embeddedJS = require('./embeddedJS');

  if (global.window != null) {
    global.window.mapReporting = {
      generateMap: function(config, zones, image) {
        embeddedJS.setClientScope(this, config.labels);
        return module.exports.generateMap(config, zones, image);
      }
    };
  }

}).call(this);
