// Generated by CoffeeScript 1.6.3
(function() {
  var lpad;

  exports.strRepeat = function(str, nb) {
    return new Array(nb + 1).join(str);
  };

  lpad = function(str, pad, len) {
    return (str.length < len ? strRepeat(pad, len - str.length) : "") + str;
  };

  exports.toHTML = function(str) {
    return str.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#39;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  };

  exports.getColor = function(val, color, invert) {
    var b, g, r;
    if (invert == null) {
      invert = false;
    }
    if (invert) {
      val = 100 - val;
    }
    color = color.toLowerCase();
    if (color === "blue") {
      r = -(57 * Math.pow(val, 4) - 12350 * Math.pow(val, 3) + 729375 * Math.pow(val, 2) + 5093750 * val - 1350000000) / 9375000;
      g = -(31 * Math.pow(val, 4) - 6790 * Math.pow(val, 3) + 457625 * Math.pow(val, 2) - 6481250 * val - 403125000) / 1875000;
      b = -(13 * Math.pow(val, 4) - 3190 * Math.pow(val, 3) + 240875 * Math.pow(val, 2) - 4156250 * val - 440625000) / 1875000;
    } else if (color === "red") {
      r = (19 * Math.pow(val, 4) - 4950 * Math.pow(val, 3) + 295625 * Math.pow(val, 2) - 7593750 * val + 2390625000) / 9375000;
      g = (23 * Math.pow(val, 4) - 3350 * Math.pow(val, 3) + 173125 * Math.pow(val, 2) - 18343750 * val + 1546875000) / 9375000;
      b = -(33 * Math.pow(val, 4) - 7250 * Math.pow(val, 3) + 474375 * Math.pow(val, 2) - 343750 * val - 1125000000) / 9375000;
    } else if (color === "green") {
      r = (23 * Math.pow(val, 4) - 3850 * Math.pow(val, 3) + 203125 * Math.pow(val, 2) - 13906250 * val + 1471875000) / 9375000;
      g = (7 * Math.pow(val, 4) - 1200 * Math.pow(val, 3) + 59375 * Math.pow(val, 2) - 4218750 * val + 914062500) / 4687500;
      b = (7 * Math.pow(val, 4) - 1230 * Math.pow(val, 3) + 66125 * Math.pow(val, 2) - 3543750 * val + 277500000) / 1875000;
    }
    return "#" + lpad(Math.round(r).toString(16), "0", 2) + lpad(Math.round(g).toString(16), "0", 2) + lpad(Math.round(b).toString(16), "0", 2);
  };

}).call(this);
