// Generated by CoffeeScript 1.6.3
(function() {
  var Node;

  Node = (require("./Node")).Node;

  exports.SVG = (function() {
    function SVG() {
      this.head = new Node(null, "svg");
      this.head.setAttributes({
        id: "head",
        version: "1.1",
        baseProfile: "full",
        xmlns: "http://www.w3.org/2000/svg",
        "xmlns:xlink": "http://www.w3.org/1999/xlink"
      });
      this.defs = new Node(this.head, "defs");
    }

    SVG.prototype.addDef = function(def, id) {
      def.setAttributes({
        "id": "f" + id
      });
      def.setParent(this.defs);
      return "f" + id;
    };

    SVG.prototype.setEmbeddedJS = function(js) {
      var script;
      script = new Node(this.head, "script", "", js);
      script.setAttributes({
        "type": "text/javascript"
      });
      return this;
    };

    SVG.prototype._addChild = function(obj) {
      this.head._addChild(obj);
      return this;
    };

    SVG.prototype.setAttributes = function(obj) {
      var k, v;
      for (k in obj) {
        v = obj[k];
        this.head.attributes[k] = v;
      }
      return this;
    };

    SVG.prototype.toString = function() {
      return "<?xml version=\"1.0\" standalone=\"no\"?>\n" + this.head.toString(0);
    };

    SVG.prototype.toDOM = function(containerID, d3) {
      var el;
      el = d3.select("#" + containerID);
      this.head.toDOM(el);
      return this;
    };

    return SVG;

  })();

}).call(this);
